const SPICES = [
    {
        "id": "cummin",
        "category": "Agro / Spices",
        "title": "Cummin Seeds (Jeera)",
        "description": "Premium export quality Cumin Seed, machine cleaned and graded for purity, aroma, and shelf stability.",
        "image": "images/cummin.webp",
        "Purity": "99%",
        "artificial color or preservatives": "No",
        "Packaging": "100g, 500g, 1kg, 25kg (custom available)",
        "Shelf Life": "12–24 months",
        "hscode": "090931",
        "Moisture": "<10%",
        "Origin": "Gujarat / Rajasthan",
        "Domestic": "25kg",
        "Export": "100kg",
        "Admixture": "1%",
        "Port": "Mundra / Nhava Sheva",
        "Capacity": "500 MT / Month",
        "Fumigation & Phytosanitary available": "Yes",
        "certifications": "Spices Board, FSSAI"
    },
    {
        "id": "red-chillies",
        "category": "Agro / Spices",
        "title": "Red Chillies",
        "description": "Premium export quality Cassia (Cinnamon), machine cleaned and graded for purity, aroma,and shelf stability.",
        "image": "images/chilly-dried-red-chilies.webp",
        "Purity": "99%",
        "artificial color or preservatives": "No",
        "Packaging": "100g, 500g, 1kg, 25kg (custom available)",
        "Shelf Life": "12–24 months",
        "hscode": "090421",
        "Moisture": "<12%",
        "Origin": "Kerala / Tamil Nadu",
        "Domestic": "25kg",
        "Export": "100kg",
        "Admixture": "1%",
        "Port": "Mundra / Nhava Sheva",
        "Capacity": "500 MT / Month",
        "Fumigation & Phytosanitary available": "Yes",
        "certifications": "Spices Board, FSSAI"
    },
    {
        "id": "cassia-cinnamon",
        "category": "Agro / Spices",
        "title": "Cassia (Cinnamon)",
        "description": "Premium export quality Cassia (Cinnamon), machine cleaned and graded for purity, aroma, and shelf stability.",
        "image": "images/cassia-cinnamon.webp",
        "Purity": "99%",
        "artificial color or preservatives": "No",
        "Packaging": "100g, 500g, 1kg, 25kg (custom available)",
        "Shelf Life": "12–24 months",
        "hscode": "090611",
        "Moisture": "<12%",
        "Origin": "Kerala / Tamil Nadu",
        "Domestic": "25kg",
        "Export": "100kg",
        "Admixture": "1%",
        "Port": "Mundra / Nhava Sheva",
        "Capacity": "500 MT / Month",
        "Fumigation & Phytosanitary available": "Yes",
        "certifications": "Spices Board, FSSAI"
    },
    {
        "id": "fennel-seeds",
        "category": "Agro / Spices",
        "title": "Fennel Seeds (Saunf)",
        "description": "Premium export quality Fennel Seed, machine cleaned and graded for purity, aroma, and shelf stability.",
        "image": "images/fennel-seed.webp",
        "Purity": "99%",
        "artificial color or preservatives": "No",
        "Packaging": "100g, 500g, 1kg, 25kg (custom available)",
        "Shelf Life": "12–24 months",
        "hscode": "090961",
        "Moisture": "<10%",
        "Origin": "Gujarat / Rajasthan",
        "Domestic": "25kg",
        "Export": "100kg",
        "certifications": "Spices Board, CE Certified, ISO 13485, ISO 9001",
    },
    {
        "id": "coriander-seeds",
        "category": "Agro / Spices",
        "title": "Coriander Seeds",
        "description": "Premium export quality Coriander Seed, machine cleaned and graded for purity, aroma, and shelf stability.",
        "image": "images/coriander-seed.webp",
        "Purity": "99%",
        "artificial color or preservatives": "No",
        "Packaging": "100g, 500g, 1kg, 25kg (custom available)",
        "Shelf Life": "12–24 months",
        "hscode": "090921",
        "Moisture": "<10%",
        "Origin": "Gujarat / MP",
        "Domestic": "25kg",
        "Export": "100kg",
        "certifications": "Spices Board, CE Certified, ISO 13485, ISO 9001",
    },
    {
        "id": "black-pepper",
        "category": "Agro / Spices",
        "title": "Black Pepper",
        "description": "Premium export quality Black Pepper, machine cleaned and graded for purity, aroma, and shelf stability.",
        "image": "images/black-paper.webp",
        "Purity": "99%",
        "artificial color or preservatives": "No",
        "Packaging": "100g, 500g, 1kg, 25kg (custom available)",
        "Shelf Life": "12–24 months",
        "hscode": "090411",
        "Moisture": "<12%",
        "Origin": "Kerala / Karnataka",
        "Domestic": "25kg",
        "Export": "100kg",
        "certifications": "Spices Board, CE Certified, ISO 13485, ISO 9001",
    },
    {
        "id": "fenugreek-seeds",
        "category": "Agro / Spices",
        "title": "Fenugreek Seeds",
        "description": "Premium export quality Fenugreek Seed, machine cleaned and graded for purity, aroma, and shelf stability.",
        "image": "images/fenugreek-seed.webp",
        "Purity": "99%",
        "artificial color or preservatives": "No",
        "Packaging": "100g, 500g, 1kg, 25kg (custom available)",
        "Shelf Life": "12–24 months",
        "hscode": "091099",
        "Moisture": "<10%",
        "Origin": "Gujarat / Rajasthan",
        "Domestic": "25kg",
        "Export": "100kg",
        "certifications": "Spices Board, CE Certified, ISO 13485, ISO 9001",
    },
    {
        "id": "ajwain-seeds",
        "category": "Agro / Spices",
        "title": "Ajwain Seeds",
        "description": "Premium export quality Ajwain Seed, machine cleaned and graded for purity, aroma, and shelf stability.",
        "image": "images/ajwan-seed.webp",
        "Purity": "99%",
        "artificial color or preservatives": "No",
        "Packaging": "100g, 500g, 1kg, 25kg (custom available)",
        "Shelf Life": "12–24 months",
        "hscode": "091099",
        "Moisture": "<10%",
        "Origin": "Gujarat / Rajasthan",
        "Domestic": "25kg",
        "Export": "100kg",
        "certifications": "Spices Board, CE Certified, ISO 13485, ISO 9001",
    },
    {
        "id": "alleppey-green",
        "category": "Agro / Spices",
        "title": "Alleppey Green Cardamom",
        "description": "Premium export quality Alleppey Green Cardamom, machine cleaned and graded for purity, aroma, and shelf stability.",
        "image": "images/alleppey-green.webp",
        "Purity": "99%",
        "artificial color or preservatives": "No",
        "Packaging": "100g, 500g, 1kg, 25kg (custom available)",
        "Shelf Life": "12–24 months",
        "hscode": "090831",
        "Moisture": "<12%",
        "Origin": "Kerala",
        "Domestic": "25kg",
        "Export": "100kg",
        "certifications": "Spices Board, CE Certified, ISO 13485, ISO 9001",
    },
    {
        "id": "dried-ginger",
        "category": "Agro / Spices",
        "title": "Dried Ginger",
        "description": "Premium export quality Dried Ginger, machine cleaned and graded for purity, aroma, and shelf stability.",
        "image": "images/dried-ginger.webp",
        "Purity": "99%",
        "artificial color or preservatives": "No",
        "Packaging": "100g, 500g, 1kg, 25kg (custom available)",
        "Shelf Life": "12–24 months",
        "hscode": "091011",
        "Moisture": "<10%",
        "Origin": "Kerala / Karnataka",
        "Domestic": "25kg",
        "Export": "100kg",
        "certifications": "Spices Board, CE Certified, ISO 13485, ISO 9001",
    },
    {
        "id": "turmeric",
        "category": "Agro / Spices",
        "title": "Turmeric",
        "description": "Premium export quality Turmeric, machine cleaned and graded for purity, aroma, and shelf stability.",
        "image": "images/turmeric.webp",
        "Purity": "99%",
        "artificial color or preservatives": "No",
        "Packaging": "100g, 500g, 1kg, 25kg (custom available)",
        "Shelf Life": "12–24 months",
        "hscode": "091030",
        "Moisture": "<10%",
        "Origin": "Telangana / Maharashtra",
        "Domestic": "25kg",
        "Export": "100kg",
        "certifications": "Spices Board, CE Certified, ISO 13485, ISO 9001",
    },
    {
        "id": "clove",
        "category": "Agro / Spices",
        "title": "Clove",
        "description": "Premium export quality Clove, machine cleaned and graded for purity, aroma, and shelf stability.",
        "image": "images/clove.webp",
        "Purity": "99%",
        "artificial color or preservatives": "No",
        "Packaging": "100g, 500g, 1kg, 25kg (custom available)",
        "Shelf Life": "12–24 months",
        "hscode": "090710",
        "Moisture": "<12%",
        "Origin": "Tamil Nadu",
        "Domestic": "25kg",
        "Export": "100kg",
        "certifications": "Spices Board, CE Certified, ISO 13485, ISO 9001",
    },
    {
        "id": "mustard-seeds",
        "category": "Agro / Spices",
        "title": "Mustard Seeds",
        "description": "Premium export quality Mustard Seed, machine cleaned and graded for purity, aroma, and shelf stability.",
        "image": "images/mustard.webp",
        "Purity": "99%",
        "artificial color or preservatives": "No",
        "Packaging": "100g, 500g, 1kg, 25kg (custom available)",
        "Shelf Life": "12–24 months",
        "hscode": "120750",
        "Moisture": "<10%",
        "Origin": "Rajasthan / MP",
        "Domestic": "25kg",
        "Export": "100kg",
        "certifications": "Spices Board, CE Certified, ISO 13485, ISO 9001",
    },
    {
        "id": "psyllium-husk",
        "category": "Agro / Spices",
        "title": "Psyllium Husk",
        "description": "Premium export quality Psyllium Husk, machine cleaned and graded for purity, aroma, and shelf stability.",
        "image": "images/psyllium-husk.webp",
        "Purity": "99%",
        "artificial color or preservatives": "No",
        "Packaging": "100g, 500g, 1kg, 25kg (custom available)",
        "Shelf Life": "12–24 months",
        "hscode": "121190",
        "Moisture": "<10%",
        "Origin": "Gujarat",
        "Domestic": "25kg",
        "Export": "100kg",
        "certifications": "Spices Board, CE Certified, ISO 13485, ISO 9001",
    }
];
